### ISSUE TITLE
No Stable Version

### ISSUE THREAD

**Issue by Dswanson803** [SahAssar/bolt-foxycart#1]
Noticed no stable version when trying to extend to this through bolt, any idea when/if it will be available? 

<img width="603" alt="outdated" src="https://cloud.githubusercontent.com/assets/13983464/22527337/d2edf4b4-e89c-11e6-8297-6926df2ee433.png">

**Comment by SahAssar** [comment]
@Dswanson803 No, this extension is not going to be developed further. I am building one that will replace it (but with stripe instead of foxycart), and the current version of this would only be compatible with bolt 2.2 anyway.

**Comment by SahAssar** [comment]
@Dswanson803 Btw, sorry if that came off as curt, but this extension has been off my priority list for about a year now, if you feel like taking it over I'd be happy to hand the repo over to you.

**Comment by Dswanson803** [comment]
@SahAssar No problem I am new to Bolt and just exploring my options, I actually just talked to you on Slack. As far as taking the project over, I have a lot on my plate atm, but I might get back to you.

**Comment by SahAssar** [comment]
Closing this, I'll add a note to the readme and remove from the extension store soon to make it more clear that it won't be a viable option going forward.
